#!/bin/sh

SERVICE_EXEC="/usr/sbin/service"
[ -x "$SERVICE_EXEC" ] || SERVICE_EXEC="/sbin/service"

TOMCAT7_SERVICE="[[tomcat7.service]]"

# Starting Tomcat 7 service
"$SERVICE_EXEC" "$TOMCAT7_SERVICE" "start"
