#!/bin/sh
### BEGIN INIT INFO
# Provides:          DirectDNSServer
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start DirectDNSServer
# Description:       Start the Direct DNS server.
### END INIT INFO

. "/etc/environment"

"$DIRECT_HOME/DirectDNSServices/DirectDNSServer/bin/DirectDNSServer" "$@"
