#!/bin/sh
### BEGIN INIT INFO
# Provides:          james3
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Apache James 3
# Description:       Start the Apache James 3 mail server.
### END INIT INFO

. "/etc/environment"

"$DIRECT_HOME/apache-james-3.0-beta4/bin/james" "$@"
